auth_url: 'http://10.0.1.132:35357/v3'
username: 'admin'
password: '2IrFRmtszQkJnzEvwBrk0giZzxImCdiVaD5WZPGb'
project_name: 'admin'
project_domain_name: 'Default'
user_domain_name: 'Default'
cert_verify: 'False'

